apiVersion: v1
kind: Service
metadata:
  name: access-management
spec:
  type: NodePort
  ports:
  - name: access-management-api
    nodePort: 31291
    port: 8080
    targetPort: 8080
  selector:
    app: access-management-api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-management-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: access-management-api
  template:
    metadata:
      labels:
        app: access-management-api
    spec:
      containers:
      - name: access-management-api
        image: chkarunakarreddy/assignment:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_PROFILES_ACTIVE
        resources:
          requests:
            cpu: 300m
            memory: 300Mi
        ports:
        - containerPort: 8090
          #        readinessProbe:
          #          tcpSocket:
          #            port: 8090
          #          initialDelaySeconds: 5
          #          periodSeconds: 10
          #          timeoutSeconds: 2
          #          failureThreshold: 1
          #          successThreshold: 1
          #        livenessProbe:
          #          tcpSocket:
          #            port: 8090
          #          initialDelaySeconds: 15
          #          periodSeconds: 20
          #          timeoutSeconds: 2
          #          failureThreshold: 1
          #          successThreshold: 1
          #      imagePullSecrets:
          #      - name: gitlab-auth
          #
